### ISSUE TITLE
submit_comment using the cookie value

### ISSUE THREAD

**Issue by ssj7** [pimedia/json-api-auth#1]
Hello sorry if this is the wrong place to ask, I already got the nonce using get_nonce and generated the cookie using generate_auth_cookie
I'm looking for something like:
http://mywebsite.com/?json=submit_comment&post_id=123&cookie=Username|1404316251|f62c592f161c88fe9c5aa5fabf5782aa&content=Comment!
or
http://mywebsite.com/?json=submit_comment&post_id=123&username=Username&password=Password&content=Comment!

I know can use get_currentuserinfo + the cookie to get the user info and then use them as in http://mywebsite.com/?json=submit_comment&post_id=123&=name=Username&email=Useremail&content=Nice! but I have a feeling that there is a simpler way.

Also please if I may ask again can the browser's cookie be set using these methods? if so how about a permanent cookie (like the 'remember me' tick) thanks in advance! I'm looking forward to hearing from you.

**Comment by emmjk** [comment]
Oky , i know this can be out of topic but , just need to ask a quick question , is this plugin functionality goes beyond the JSON Api User plugin that you also made ? Am currently using JSON Api User plugin . What would you recommend ?

**Comment by pimedia** [comment]
No, all the endpoints of this Auth plugin are already made part of JSON API User plugin.
Thanks
    On Friday, April 13, 2018, 4:58:35 AM GMT+5, Emmjk <notifications@github.com> wrote:  
 
 
Oky , i know this can be out of topic but , just need to ask a quick question , is this plugin functionality goes beyond the JSON Api User plugin that you also made ? Am currently using JSON Api User plugin . What would you recommend ?
