### ISSUE TITLE
404 on nginx

### ISSUE THREAD

**Issue by ciprianimike** [pimedia/json-api-auth#4]
Wordpress 4.9 on Nginx, while default REST API  and JSON API are working, both with permalinks or simple urls, activating auth and user controllers, the endpoints /user/* and  /auth/* return 404.

**Comment by pimedia** [comment]
http://www.wppim.com/api/user/info/

http://www.wppim.com/api/auth/validate_auth_cookie/

working on 4.9 just fine. server is nginx too.
    On Saturday, November 18, 2017, 11:26:05 PM GMT+5, Michele Cipriani <notifications@github.com> wrote:  
 
 
Wordpress 4.9 on Nginx, while default REST API and JSON API are working, both with permalinks or simple urls, activating auth and user controllers, the endpoints /user/* and /auth/* return 404.

**Comment by ciprianimike** [comment]
Ok, thank you.

The problem was the requests on plain http without setting insicure=cool, but I didn't receive the message, I am going to inspect this.

**Comment by ciprianimike** [comment]
Ok, thank you.

The problem was the requests on plain http without setting insicure=cool, but I didn't receive the message, I am going to inspect this.
